title: Memories of Two Cities
title-abbreviated: Memories of Two Cities
description: '"‘Memories of Two Cities’ is a pictorial exhibition jointly
  presented by the Capital Library of China and the National Library of
  Singapore, signifying the goodwill and partnership between the two
  institutions."'
url: https://memoriesoftwocities.nlb.gov.sg
google_analytics: UA-50449401-29
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
favicon: /images/memories-of-two-cities-icon.ico
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
colors:
  primary-color: "#cf4000"
  secondary-color: "#cf4000"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
staging: https://staging.d2yvmpuvamjxdy.amplifyapp.com/
prod: https://master.d2yvmpuvamjxdy.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
google_analytics_ga4: G-LWNLM0PL9J
linkedin-insights: ""
